### ISSUE TITLE
Differences in Matlab and C implementation

### ISSUE THREAD

**Issue by hochej** [cvxgrp/aa#4]
Hi,

thanks for the interesting work and providing the code. I have a few questions about the differences between the Matlab implementation (https://github.com/cvxgrp/nonexp_global_aa1/blob/master/codes/algorithms/alg_iter.m) and the C implementation. 

### Safeguarding: 

In the Matlab implementation, safeguarding is done as presented in the paper (Algorithm 3.1, line 12):

```matlab        
Ubar0 = norm(g0);
if Ubar0 <= D * Ubar * (count+1)^(-1-epsilon) || i == 1
    % accept
else 
    % reject -> vanilla iteration
```

Whereas in the C implementation, the norm || gk ||2 from the current solution is compared to the norm || gk-1 ||2 of the previous solution. 

```c
  if (norm_diff > a->safeguard_factor * a->norm_g) {
    /* in this case we reject the AA step and reset */
    memcpy(f_new, a->f, a->dim * sizeof(aa_float));
    memcpy(x_new, a->x, a->dim * sizeof(aa_float));
  }
```
Have you found that one of the two safeguarding criteria works better and is therefore recommended, or are they identical and I just overlooked this? 

### Update of x^(k+1)
Do I understand the code correctly that in Matlab x is updated according to the AA algorithm from the second iteration on? 
```matlab
if i == 1
    x1 = Fx0;
else
    x1 = x0 - H_AA(g0, H_vecs1, H_vecs2);
end
```
Whereas in the C implementation, this only happens when the number of iterations is greater than or equal to memory?
```c 
/* only perform solve steps when the memory is full */
if (!FILL_MEMORY_BEFORE_SOLVE || a->iter >= a->mem) {
  /* set M = S'Y or Y'Y depending on type of aa used */
  set_m(a, len);
  /* solve linear system, new point overwrites f if successful */
  aa_norm = solve(f, a, len);
}
```
Is there a reason that in the steps where the number of iterations is less than the memory, the linear system of equations is not solved? In these cases, the new `x` (x^(k+1)) is then determined by f(x) or? Is there a reason that alpha of the KM operator, (1-alpha) * x^k + alpha * f(x) is fixed to 1?

**Comment by junziz** [comment]
Thanks a lot for your questions! First of all, you are right that we indeed implemented different stabilization tricks in the C and the Matlab versions. The reason is because we are still experimenting to find better and better stabilization tricks. 

In fact, the C implementation can be seen as a heuristically simplified version of the Matlab version that is easier to implement yet already works pretty well in practice. It builds upon the stabilization ideas (regularization, safeguarding and restarting) of the Matlab implementation (which is the same as the one in our paper) but simplified them in many ways. 

In particular, we drop the restarting technique and simplify the Powell's regularization to a simple Levenberg-Marquardt style regularization accordingly. Due to these simplifications, the theoretical guarantees obtained in our paper may not always hold, and so the safeguarding criteria is also modified accordingly to be more conservative (checking decrease in consecutive residuals) to be "safer". It works well but may or may not be better than the original safeguard depending on problems. This is why you see the first difference about "safeguarding". 

As for the second difference about "update of x^{k+1}", it's because of the aforementioned removal of the restarting technique. In the Matlab implementation, due to the restarting mechanism, the AA memory starts from 1 and increases until either the max memory or ill-conditioning is reached, and then is reset to 1. Hence the AA updates start from the second iteration. For the C implementation, the AA memory is fixed to the max-memory and so we have to reach the iteration = max-memory to start the first AA update. And yes, so when the iteration number < max-memory, the new x (x^(k+1)) is then determined by f(x) as you mentioned.  

For your last few question, by alpha, do you mean the relaxation term here: https://github.com/cvxgrp/aa/blob/master/src/aa.c#L237? If so, then the reason for choosing \alpha = 1 is simply because that it indeed works well in practice, as is also observed in the classical paper https://users.wpi.edu/~walker/Papers/Walker-Ni,SINUM,V49,1715-1735.pdf. That being said, other choices may also work and may work better as well. Some other choices of alpha can be found in https://arxiv.org/abs/1809.02341 and https://onlinelibrary.wiley.com/doi/abs/10.1002/nla.617. (Note that these works all denote alpha as beta instead.)

Hope that these explanations answer your questions and feel free to let us know if there is still anything unclear. Thanks!

**Comment by hochej** [comment]
Thank you for the quick and very helpful reply!
One thing is still a little unclear to me. You said:
> For the C implementation, the AA memory is fixed to the max-memory and so we have to reach the iteration = max-memory to start the first AA update.

What is the reason here that iteration = max-memory has be reached to start AA update? Is this a more technical reason that in C an array is allocated with the fixed size of max-memory? 
In case that the function call, f(x), is much more expensive than the AA update, are there reasons not to start with AA update from the second iteration on?

**Comment by junziz** [comment]
Yes you are right! This is not an essential restriction. It's more of an implementation choice for simplicity in C coding. And you can definitely start with AA updates from the second iteration on and accordingly increase the memory all the way up to the max memory and then stick to the max memory thereafter. Hope that this answers your question :)

**Comment by bodono** [comment]
You can switch behaviors using the macro `FILL_MEMORY_BEFORE_SOLVE`  defined [here](https://github.com/cvxgrp/aa/blob/master/src/aa.c#L30). If that is set to `0`, then it will begin the AA updates immediately, otherwise it waits until it fills the memory before doing the updates. The main reason it defaults to filling the memory is just to amortize the cost if AA is consistently failing to provide a good update, since if an AA update is rejected it resets the entire procedure (see [here](https://github.com/cvxgrp/aa/blob/master/src/aa.c#L420)) and will therefore wait `mem` steps before doing another update.

**Comment by hochej** [comment]
Thank you both, for the explanations. This has helped me a lot! 
One last question I have: In the `relax` function, you calculate both `relaxation * f` and `(1-relaxation) * x`, where `relaxation` is a scalar and `f` (`x`) are vectors or not? 
Is it correct that in the calls of the BLAS functions (in line [248 ](https://github.com/cvxgrp/aa/blob/107a5081ee2f0056781c2b2198da8fe50b2c898a/src/aa.c#L248 )and line [250](https://github.com/cvxgrp/aa/blob/107a5081ee2f0056781c2b2198da8fe50b2c898a/src/aa.c#L250)) `blen` and not `bdim` is passed as dimension? Currently, for example, in the second iteration (`iter == 1`) only the first element of the vector is scaled or? But shouldn't the whole vector be scaled and `bdim` be used as the argument?

**Comment by bodono** [comment]
Good spot, that's a bug! Thanks for letting us know, here is a PR to fix it: https://github.com/cvxgrp/aa/pull/5/files

**Comment by hochej** [comment]
Thanks for the quick reply and the fix. Then I will close the issue.
